[package]
name = "comic_thumbgen"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
zip = "0.6"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
url = "2.5"
walkdir = "2.4"
