[package]
name = "cbz_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23"
egui_extras = "0.23"
image = "0.24"
zip = "0.6"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
rfd = "0.9"
