[package]
name = "cbz_thumbnail_provider"
version = "0.1.0"
edition = "2021"

[lib]
name = "cbz_thumbnail_provider"
crate-type = ["cdylib"]  # DLL output

[dependencies]
windows = { version = "0.48", features = [
    "Win32_System_Com",
    "Win32_Graphics_Imaging",
    "Win32_UI_Shell",
] }